//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClient.BlackJackWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserWcf", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWCF")]
    [System.SerializableAttribute()]
    public partial class UserWcf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int moneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numOfGamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                if ((this.isAdminField.Equals(value) != true)) {
                    this.isAdminField = value;
                    this.RaisePropertyChanged("isAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int money {
            get {
                return this.moneyField;
            }
            set {
                if ((this.moneyField.Equals(value) != true)) {
                    this.moneyField = value;
                    this.RaisePropertyChanged("money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numOfGames {
            get {
                return this.numOfGamesField;
            }
            set {
                if ((this.numOfGamesField.Equals(value) != true)) {
                    this.numOfGamesField = value;
                    this.RaisePropertyChanged("numOfGames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameWcf", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWCF")]
    [System.SerializableAttribute()]
    public partial class GameWcf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numOfPlayersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstUser {
            get {
                return this.FirstUserField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstUserField, value) != true)) {
                    this.FirstUserField = value;
                    this.RaisePropertyChanged("FirstUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondUser {
            get {
                return this.SecondUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondUserField, value) != true)) {
                    this.SecondUserField = value;
                    this.RaisePropertyChanged("SecondUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numOfPlayers {
            get {
                return this.numOfPlayersField;
            }
            set {
                if ((this.numOfPlayersField.Equals(value) != true)) {
                    this.numOfPlayersField = value;
                    this.RaisePropertyChanged("numOfPlayers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlackJackWebService.Service", CallbackContract=typeof(WinClient.BlackJackWebService.ServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/login", ReplyAction="http://tempuri.org/Service/loginResponse")]
        void login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/loginWeb", ReplyAction="http://tempuri.org/Service/loginWebResponse")]
        WinClient.BlackJackWebService.UserWcf loginWeb(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/logout", ReplyAction="http://tempuri.org/Service/logoutResponse")]
        bool logout(WinClient.BlackJackWebService.UserWcf user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/updateUser", ReplyAction="http://tempuri.org/Service/updateUserResponse")]
        bool updateUser(WinClient.BlackJackWebService.UserWcf u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/addGame", ReplyAction="http://tempuri.org/Service/addGameResponse")]
        void addGame(string IP, WinClient.BlackJackWebService.UserWcf user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/RemoveGameByUser", ReplyAction="http://tempuri.org/Service/RemoveGameByUserResponse")]
        bool RemoveGameByUser(WinClient.BlackJackWebService.UserWcf user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/RemoveGameByIP", ReplyAction="http://tempuri.org/Service/RemoveGameByIPResponse")]
        void RemoveGameByIP(string IP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetGames", ReplyAction="http://tempuri.org/Service/GetGamesResponse")]
        WinClient.BlackJackWebService.GameWcf[] GetGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/getUser", ReplyAction="http://tempuri.org/Service/getUserResponse")]
        WinClient.BlackJackWebService.UserWcf getUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/addUser", ReplyAction="http://tempuri.org/Service/addUserResponse")]
        bool addUser(WinClient.BlackJackWebService.UserWcf user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/getUsers", ReplyAction="http://tempuri.org/Service/getUsersResponse")]
        WinClient.BlackJackWebService.UserWcf[] getUsers();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Service/updateGames")]
        void updateGames(string action, WinClient.BlackJackWebService.GameWcf game);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/Service/loginCallback")]
        void loginCallback(WinClient.BlackJackWebService.UserWcf user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceChannel : WinClient.BlackJackWebService.Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<WinClient.BlackJackWebService.Service>, WinClient.BlackJackWebService.Service {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void login(string username, string password) {
            base.Channel.login(username, password);
        }
        
        public WinClient.BlackJackWebService.UserWcf loginWeb(string username, string password) {
            return base.Channel.loginWeb(username, password);
        }
        
        public bool logout(WinClient.BlackJackWebService.UserWcf user) {
            return base.Channel.logout(user);
        }
        
        public bool updateUser(WinClient.BlackJackWebService.UserWcf u) {
            return base.Channel.updateUser(u);
        }
        
        public void addGame(string IP, WinClient.BlackJackWebService.UserWcf user) {
            base.Channel.addGame(IP, user);
        }
        
        public bool RemoveGameByUser(WinClient.BlackJackWebService.UserWcf user) {
            return base.Channel.RemoveGameByUser(user);
        }
        
        public void RemoveGameByIP(string IP) {
            base.Channel.RemoveGameByIP(IP);
        }
        
        public WinClient.BlackJackWebService.GameWcf[] GetGames() {
            return base.Channel.GetGames();
        }
        
        public WinClient.BlackJackWebService.UserWcf getUser(string username) {
            return base.Channel.getUser(username);
        }
        
        public bool addUser(WinClient.BlackJackWebService.UserWcf user, string password) {
            return base.Channel.addUser(user, password);
        }
        
        public WinClient.BlackJackWebService.UserWcf[] getUsers() {
            return base.Channel.getUsers();
        }
    }
}
