//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace BlackJackDB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BlackJackDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BlackJackDataEntities object using the connection string found in the 'BlackJackDataEntities' section of the application configuration file.
        /// </summary>
        public BlackJackDataEntities() : base("name=BlackJackDataEntities", "BlackJackDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlackJackDataEntities object.
        /// </summary>
        public BlackJackDataEntities(string connectionString) : base(connectionString, "BlackJackDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlackJackDataEntities object.
        /// </summary>
        public BlackJackDataEntities(EntityConnection connection) : base(connection, "BlackJackDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Game> Game
        {
            get
            {
                if ((_Game == null))
                {
                    _Game = base.CreateObjectSet<Game>("Game");
                }
                return _Game;
            }
        }
        private ObjectSet<Game> _Game;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Game EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGame(Game game)
        {
            base.AddObject("Game", game);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackJackDataModel", Name="Game")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Game : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Game object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="firstUser">Initial value of the FirstUser property.</param>
        /// <param name="numOfUsers">Initial value of the NumOfUsers property.</param>
        /// <param name="secondUser">Initial value of the SecondUser property.</param>
        public static Game CreateGame(global::System.Int32 id, global::System.String iP, global::System.String firstUser, global::System.Int32 numOfUsers, global::System.String secondUser)
        {
            Game game = new Game();
            game.ID = id;
            game.IP = iP;
            game.FirstUser = firstUser;
            game.NumOfUsers = numOfUsers;
            game.SecondUser = secondUser;
            return game;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstUser
        {
            get
            {
                return _FirstUser;
            }
            set
            {
                OnFirstUserChanging(value);
                ReportPropertyChanging("FirstUser");
                _FirstUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstUser");
                OnFirstUserChanged();
            }
        }
        private global::System.String _FirstUser;
        partial void OnFirstUserChanging(global::System.String value);
        partial void OnFirstUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumOfUsers
        {
            get
            {
                return _NumOfUsers;
            }
            set
            {
                OnNumOfUsersChanging(value);
                ReportPropertyChanging("NumOfUsers");
                _NumOfUsers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumOfUsers");
                OnNumOfUsersChanged();
            }
        }
        private global::System.Int32 _NumOfUsers;
        partial void OnNumOfUsersChanging(global::System.Int32 value);
        partial void OnNumOfUsersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecondUser
        {
            get
            {
                return _SecondUser;
            }
            set
            {
                OnSecondUserChanging(value);
                ReportPropertyChanging("SecondUser");
                _SecondUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecondUser");
                OnSecondUserChanged();
            }
        }
        private global::System.String _SecondUser;
        partial void OnSecondUserChanging(global::System.String value);
        partial void OnSecondUserChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackJackDataModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="money">Initial value of the money property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String username, global::System.String password, global::System.Int32 money)
        {
            User user = new User();
            user.ID = id;
            user.username = username;
            user.password = password;
            user.money = money;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 money
        {
            get
            {
                return _money;
            }
            set
            {
                OnmoneyChanging(value);
                ReportPropertyChanging("money");
                _money = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("money");
                OnmoneyChanged();
            }
        }
        private global::System.Int32 _money;
        partial void OnmoneyChanging(global::System.Int32 value);
        partial void OnmoneyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numOfGames
        {
            get
            {
                return _numOfGames;
            }
            set
            {
                OnnumOfGamesChanging(value);
                ReportPropertyChanging("numOfGames");
                _numOfGames = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numOfGames");
                OnnumOfGamesChanged();
            }
        }
        private Nullable<global::System.Int32> _numOfGames;
        partial void OnnumOfGamesChanging(Nullable<global::System.Int32> value);
        partial void OnnumOfGamesChanged();

        #endregion
    
    }

    #endregion
    
}
