//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJackWeb.BJServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserWcf", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWCF")]
    [System.SerializableAttribute()]
    public partial class UserWcf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int moneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numOfGamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                if ((this.isAdminField.Equals(value) != true)) {
                    this.isAdminField = value;
                    this.RaisePropertyChanged("isAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int money {
            get {
                return this.moneyField;
            }
            set {
                if ((this.moneyField.Equals(value) != true)) {
                    this.moneyField = value;
                    this.RaisePropertyChanged("money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numOfGames {
            get {
                return this.numOfGamesField;
            }
            set {
                if ((this.numOfGamesField.Equals(value) != true)) {
                    this.numOfGamesField = value;
                    this.RaisePropertyChanged("numOfGames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameWcf", Namespace="http://schemas.datacontract.org/2004/07/BlackJackWCF")]
    [System.SerializableAttribute()]
    public partial class GameWcf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numOfPlayersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstUser {
            get {
                return this.FirstUserField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstUserField, value) != true)) {
                    this.FirstUserField = value;
                    this.RaisePropertyChanged("FirstUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondUser {
            get {
                return this.SecondUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondUserField, value) != true)) {
                    this.SecondUserField = value;
                    this.RaisePropertyChanged("SecondUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numOfPlayers {
            get {
                return this.numOfPlayersField;
            }
            set {
                if ((this.numOfPlayersField.Equals(value) != true)) {
                    this.numOfPlayersField = value;
                    this.RaisePropertyChanged("numOfPlayers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BJServiceRef.IBJService")]
    public interface IBJService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/login", ReplyAction="http://tempuri.org/IBJService/loginResponse")]
        BlackJackWeb.BJServiceRef.UserWcf login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/logout", ReplyAction="http://tempuri.org/IBJService/logoutResponse")]
        bool logout(BlackJackWeb.BJServiceRef.UserWcf user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/updateUser", ReplyAction="http://tempuri.org/IBJService/updateUserResponse")]
        bool updateUser(BlackJackWeb.BJServiceRef.UserWcf u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/addGame", ReplyAction="http://tempuri.org/IBJService/addGameResponse")]
        BlackJackWeb.BJServiceRef.GameWcf addGame(string IP, BlackJackWeb.BJServiceRef.UserWcf user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/RemoveGameByUser", ReplyAction="http://tempuri.org/IBJService/RemoveGameByUserResponse")]
        bool RemoveGameByUser(BlackJackWeb.BJServiceRef.UserWcf user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/RemoveGameByIP", ReplyAction="http://tempuri.org/IBJService/RemoveGameByIPResponse")]
        bool RemoveGameByIP(string IP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/GetGames", ReplyAction="http://tempuri.org/IBJService/GetGamesResponse")]
        BlackJackWeb.BJServiceRef.GameWcf[] GetGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/getUser", ReplyAction="http://tempuri.org/IBJService/getUserResponse")]
        BlackJackWeb.BJServiceRef.UserWcf getUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/addUser", ReplyAction="http://tempuri.org/IBJService/addUserResponse")]
        bool addUser(BlackJackWeb.BJServiceRef.UserWcf user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBJService/getUsers", ReplyAction="http://tempuri.org/IBJService/getUsersResponse")]
        BlackJackWeb.BJServiceRef.UserWcf[] getUsers();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBJServiceChannel : BlackJackWeb.BJServiceRef.IBJService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BJServiceClient : System.ServiceModel.ClientBase<BlackJackWeb.BJServiceRef.IBJService>, BlackJackWeb.BJServiceRef.IBJService {
        
        public BJServiceClient() {
        }
        
        public BJServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BJServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BJServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BJServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BlackJackWeb.BJServiceRef.UserWcf login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public bool logout(BlackJackWeb.BJServiceRef.UserWcf user) {
            return base.Channel.logout(user);
        }
        
        public bool updateUser(BlackJackWeb.BJServiceRef.UserWcf u) {
            return base.Channel.updateUser(u);
        }
        
        public BlackJackWeb.BJServiceRef.GameWcf addGame(string IP, BlackJackWeb.BJServiceRef.UserWcf user) {
            return base.Channel.addGame(IP, user);
        }
        
        public bool RemoveGameByUser(BlackJackWeb.BJServiceRef.UserWcf user) {
            return base.Channel.RemoveGameByUser(user);
        }
        
        public bool RemoveGameByIP(string IP) {
            return base.Channel.RemoveGameByIP(IP);
        }
        
        public BlackJackWeb.BJServiceRef.GameWcf[] GetGames() {
            return base.Channel.GetGames();
        }
        
        public BlackJackWeb.BJServiceRef.UserWcf getUser(string username) {
            return base.Channel.getUser(username);
        }
        
        public bool addUser(BlackJackWeb.BJServiceRef.UserWcf user, string password) {
            return base.Channel.addUser(user, password);
        }
        
        public BlackJackWeb.BJServiceRef.UserWcf[] getUsers() {
            return base.Channel.getUsers();
        }
    }
}
